# fun for all
settings:
  title: 'Systems Status Report'
  url: 'https://breakerbreaker.hommati.com' # used for Slack messages
  logo: logo_new_10.webp # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'Cloudflare Workers.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: chicago-web-1
    name: chicago-web-1
    description: 'Hommati Frontend Server #1 - Chicago'
    url: 'https://chicago-upgrade.hommati.com'
    method: GET
    expectStatus: 301
    linkable: false # allows the title to be a link, default=true

  - id: chicago-web-2
    name: chicago-web-2
    description: 'Hommati Frontend Server #2 - Chicago'
    url: 'https://safetynet.hommati.com'
    method: GET
    expectStatus: 301
    linkable: false # allows the title to be a link, default=true

  - id: chicago-web-3
    name: chicago-web-3
    description: 'Hommati Frontend Server #3 - Chicago'
    url: 'https://safetynet2.hommati.com'
    method: GET
    expectStatus: 301
    linkable: false # allows the title to be a link, default=true

  - id: chicago-web-4
    name: chicago-web-4
    description: 'Hommati Frontend Server #4 - Chicago'
    url: 'https://safetynet3.hommati.com'
    method: GET
    expectStatus: 301
    linkable: false # allows the title to be a link, default=true